### ISSUE TITLE
Add SYN: Synapse

### ISSUE THREAD

**Issue by QChab** [paraswap/community-token-list#6]
- [x] I understand that token listing is not required to use the ParaSwap Protocol.
- [x] I understand that filing an issue does not guarantee addition to the ParaSwap Community token list.
- [x] I understand that adding a token still requires an approval by the ParaSwap DAO to be whitelisted for ParaBoost.

**Please provide the following information for your token.**

Token infos by chain:
````
 [
    {
        "chainId": 137,
        "address": "0xf8f9efc0db77d8881500bb06ff5d6abc3070e695",
        "symbol": "SYN",
        "name": "Synapse",
        "decimals": 18,
        "logoURI": "https://assets.coingecko.com/coins/images/18024/thumb/synapse_social_icon.png?1663921797"
    },
    {
        "chainId": 10,
        "address": "0x5a5fff6f753d7c11a56a52fe47a177a87e431655",
        "symbol": "SYN",
        "name": "Synapse",
        "decimals": 18,
        "logoURI": "https://assets.coingecko.com/coins/images/18024/thumb/synapse_social_icon.png?1663921797"
    },
    {
        "chainId": 56,
        "address": "0xa4080f1778e69467e905b8d6f72f6e441f9e9484",
        "symbol": "SYN",
        "name": "Synapse",
        "decimals": 18,
        "logoURI": "https://assets.coingecko.com/coins/images/18024/thumb/synapse_social_icon.png?1663921797"
    },
    {
        "chainId": 250,
        "address": "0xe55e19fb4f2d85af758950957714292dac1e25b2",
        "symbol": "SYN",
        "name": "Synapse",
        "decimals": 18,
        "logoURI": "https://assets.coingecko.com/coins/images/18024/thumb/synapse_social_icon.png?1663921797"
    },
    {
        "chainId": 42161,
        "address": "0x080f6aed32fc474dd5717105dba5ea57268f46eb",
        "symbol": "SYN",
        "name": "Synapse",
        "decimals": 18,
        "logoURI": "https://assets.coingecko.com/coins/images/18024/thumb/synapse_social_icon.png?1663921797"
    },
]
````
List of supported chains: [chains.json](https://github.com/paraswap/community-token-list/blob/master/src/sources/chains.json "Supprted Chains").

Link to the official homepage of token: https://synapseprotocol.com/landing

Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/synapse

Moreover the current address in the list for arbitrum doesn't correspond to the official sources.

**Comment by mwamedacen** [comment]
I confirm the adresses from this source: https://docs.synapseprotocol.com/reference/contract-addresses
